#!/usr/bin/env node

/**
 * Memento Protocol — Interactive setup wizard.
 * Usage: npx memento-mcp init
 */

import readline from "node:readline";
import fs from "node:fs";
import path from "node:path";
import https from "node:https";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { DEFAULTS } from "./config.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function ask(rl, question, defaultVal) {
  const suffix = defaultVal ? ` (${defaultVal})` : "";
  return new Promise((resolve) => {
    rl.question(`${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultVal || "");
    });
  });
}

function askYesNo(rl, question, defaultYes = true) {
  const hint = defaultYes ? "Y/n" : "y/N";
  return new Promise((resolve) => {
    rl.question(`${question} [${hint}]: `, (answer) => {
      const a = answer.trim().toLowerCase();
      if (a === "") resolve(defaultYes);
      else resolve(a === "y" || a === "yes");
    });
  });
}

/** Deep-merge source into target (mutates target). */
function deepMerge(target, source) {
  for (const [key, val] of Object.entries(source)) {
    if (
      val &&
      typeof val === "object" &&
      !Array.isArray(val) &&
      target[key] &&
      typeof target[key] === "object" &&
      !Array.isArray(target[key])
    ) {
      deepMerge(target[key], val);
    } else {
      target[key] = val;
    }
  }
  return target;
}

/** POST JSON over HTTPS. Returns parsed JSON response. */
function httpsPost(url, body) {
  return new Promise((resolve, reject) => {
    const parsed = new URL(url);
    const data = JSON.stringify(body);
    const req = https.request(
      {
        hostname: parsed.hostname,
        port: parsed.port || 443,
        path: parsed.pathname,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Content-Length": Buffer.byteLength(data),
        },
      },
      (res) => {
        let chunks = "";
        res.on("data", (d) => (chunks += d));
        res.on("end", () => {
          try {
            resolve(JSON.parse(chunks));
          } catch {
            reject(new Error(`Invalid JSON from API: ${chunks}`));
          }
        });
      }
    );
    req.on("error", reject);
    req.write(data);
    req.end();
  });
}

// ---------------------------------------------------------------------------
// Instructions blob — used by headless integration and fallback print
// ---------------------------------------------------------------------------

const INSTRUCTIONS_BLOB = `## Memento Protocol

Working memory is managed by Memento. MCP tools available:
\`memento_store\`, \`memento_recall\`, \`memento_item_list\`,
\`memento_skip_add\`, \`memento_skip_check\`.

**Memory discipline — notes are instructions, not logs.**
Write: "Skip X until condition Y" — not "checked X, it was quiet."
Every memory must answer: could a future agent with zero context
read this and know exactly what to do?

Use \`memento_store\` when you learn something worth keeping.
Use \`memento_skip_add\` for things to explicitly not re-investigate.
Use \`memento_recall\` to search memories by keyword or tag.
Hooks run automatically — recall before responses, distillation
before compaction. Trust the hooks. Focus on writing good memories.`;

// ---------------------------------------------------------------------------
// Headless agent integration
// ---------------------------------------------------------------------------

const HEADLESS_CMDS = {
  "claude-code": (prompt) => ["claude", "-p", "--dangerously-skip-permissions", prompt],
  "codex":       (prompt) => ["codex", "exec", prompt],
  "gemini":      (prompt) => ["gemini", prompt],
  "opencode":    (prompt) => ["opencode", "run", prompt],
};

function buildIntegrationPrompt(blob) {
  return [
    "The following instructions were generated by memento-mcp init for this project.",
    "Add them to the file where you store persistent behavioral instructions",
    "(e.g. CLAUDE.md for Claude Code). If the file exists, read it first and",
    "integrate the new section without removing existing content. If a section",
    "with the same heading already exists, replace it. If no instructions file",
    "exists yet, create one.",
    "",
    "--- INSTRUCTIONS ---",
    blob,
    "--- END ---",
  ].join("\n");
}

function runAgentHeadless(agentKey, prompt) {
  const cmdBuilder = HEADLESS_CMDS[agentKey];
  if (!cmdBuilder) return null;
  const [cmd, ...args] = cmdBuilder(prompt);
  try {
    const result = execFileSync(cmd, args, {
      cwd: process.cwd(),
      encoding: "utf8",
      stdio: ["pipe", "pipe", "inherit"],
      timeout: 60000,
    });
    return result;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// CLI flag parsing
// ---------------------------------------------------------------------------

function parseFlags(argv) {
  const flags = { nonInteractive: false, apiKey: null };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "-y" || argv[i] === "--yes") {
      flags.nonInteractive = true;
    } else if (argv[i] === "--api-key" && argv[i + 1]) {
      flags.apiKey = argv[i + 1];
      i++;
    }
  }
  // Also check environment variable
  if (!flags.apiKey && process.env.MEMENTO_API_KEY) {
    flags.apiKey = process.env.MEMENTO_API_KEY;
  }
  return flags;
}

// ---------------------------------------------------------------------------
// File writers
// ---------------------------------------------------------------------------

function readJsonFile(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch {
    return null;
  }
}

function writeJsonFile(filePath, data) {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n");
}

/**
 * Idempotently register a hook in a settings object.
 * Works for both Claude Code and Gemini CLI (same JSON structure).
 * Returns true if a new hook was added, false if already present.
 */
function ensureHook(settings, eventName, command, timeout) {
  const existing = settings.hooks?.[eventName] || [];
  const alreadyRegistered = existing.some((entry) =>
    entry.hooks?.some((h) => h.command === command)
  );
  if (alreadyRegistered) return false;
  if (!settings.hooks) settings.hooks = {};
  settings.hooks[eventName] = [
    ...existing,
    { hooks: [{ type: "command", command, timeout }] },
  ];
  return true;
}

function appendToGitignore(cwd, line) {
  const gitignorePath = path.join(cwd, ".gitignore");
  if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, "utf8");
    if (content.includes(line)) return false; // already there
    fs.appendFileSync(gitignorePath, `\n${line}\n`);
  } else {
    fs.writeFileSync(gitignorePath, `${line}\n`);
  }
  return true;
}

// ---------------------------------------------------------------------------
// Agent registry — per-agent MCP config writers
// ---------------------------------------------------------------------------

const MCP_SERVER_ENTRY = {
  command: "npx",
  args: ["-y", "memento-mcp"],
};

function writeMcpJson(cwd) {
  const filePath = path.join(cwd, ".mcp.json");
  const existing = readJsonFile(filePath) || {};
  deepMerge(existing, { mcpServers: { memento: MCP_SERVER_ENTRY } });
  writeJsonFile(filePath, existing);
  return ".mcp.json";
}

function writeCodexToml(cwd) {
  const dir = path.join(cwd, ".codex");
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, "config.toml");

  let content = "";
  try {
    content = fs.readFileSync(filePath, "utf8");
  } catch {
    /* file doesn't exist */
  }

  // Skip if memento section already exists
  if (/\[mcp_servers\.memento\]/.test(content)) {
    return ".codex/config.toml (already configured)";
  }

  const section = `\n[mcp_servers.memento]\ncommand = "npx"\nargs = ["-y", "memento-mcp"]\n`;
  const separator = content && !content.endsWith("\n") ? "\n" : "";
  fs.writeFileSync(filePath, content + separator + section);
  return ".codex/config.toml";
}

function writeGeminiJson(cwd) {
  const dir = path.join(cwd, ".gemini");
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, "settings.json");
  const existing = readJsonFile(filePath) || {};
  deepMerge(existing, { mcpServers: { memento: MCP_SERVER_ENTRY } });
  writeJsonFile(filePath, existing);
  return ".gemini/settings.json";
}

function writeOpencodeJson(cwd) {
  const filePath = path.join(cwd, "opencode.json");
  const existing = readJsonFile(filePath) || {};
  deepMerge(existing, {
    mcp: {
      memento: {
        type: "local",
        command: ["npx", "-y", "memento-mcp"],
        enabled: true,
      },
    },
  });
  writeJsonFile(filePath, existing);
  return "opencode.json";
}

const AGENTS = {
  "claude-code": {
    name: "Claude Code",
    detect: (cwd) => fs.existsSync(path.join(cwd, ".claude")),
    configWriter: writeMcpJson,
    hasHooks: true,
    nextSteps: "Restart Claude Code to activate.",
  },
  codex: {
    name: "OpenAI Codex",
    detect: (cwd) => fs.existsSync(path.join(cwd, ".codex")),
    configWriter: writeCodexToml,
    hasHooks: false,
    nextSteps: "Run `codex` in this directory — memento tools load automatically.",
  },
  gemini: {
    name: "Gemini CLI",
    detect: (cwd) => fs.existsSync(path.join(cwd, ".gemini")),
    configWriter: writeGeminiJson,
    hasHooks: false,
    nextSteps: "Run `gemini` in this directory — memento tools load automatically.",
  },
  opencode: {
    name: "OpenCode",
    detect: (cwd) => fs.existsSync(path.join(cwd, "opencode.json")),
    configWriter: writeOpencodeJson,
    hasHooks: false,
    nextSteps: "Run `opencode` in this directory — memento tools load automatically.",
  },
};

// Exported for testing
export { AGENTS, writeMcpJson, writeCodexToml, writeGeminiJson, writeOpencodeJson };

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

async function runInit(flags = {}) {
  const { nonInteractive = false, apiKey: flagApiKey = null } = flags;
  const cwd = process.cwd();
  const projectName = path.basename(cwd);

  const rl = nonInteractive
    ? null
    : readline.createInterface({ input: process.stdin, output: process.stdout });

  console.log(`
            ▗
▛▛▌█▌▛▛▌█▌▛▌▜▘▛▌▄▖▛▛▌▛▘▛▌
▌▌▌▙▖▌▌▌▙▖▌▌▐▖▙▌  ▌▌▌▙▖▙▌
                       ▌

  hifathom.com  ·  fathom@myrakrusemark.com
`);

  // 1. Workspace name
  const workspace = nonInteractive
    ? projectName
    : await ask(rl, "Workspace name", projectName);

  // 2. API key
  let apiKey = flagApiKey || "";
  if (!nonInteractive) {
    apiKey = await ask(rl, "API key (leave blank to sign up)");
  }
  if (!apiKey) {
    if (nonInteractive) {
      // 5-second countdown warning, then auto-signup
      process.stderr.write(
        "\n  No API key provided — a new one will be generated.\n" +
        "  Press Ctrl+C to cancel.\n  "
      );
      for (let i = 5; i > 0; i--) {
        process.stderr.write(`${i}... `);
        await new Promise((r) => setTimeout(r, 1000));
      }
      process.stderr.write("\n\n");
    }
    const email = nonInteractive ? "" : await ask(rl, "Email for account recovery (optional)");
    console.log("\nSigning up...");
    try {
      const body = { workspace };
      if (email) body.email = email;
      const resp = await httpsPost(`${DEFAULTS.apiUrl}/v1/auth/signup`, body);
      if (resp.api_key) {
        apiKey = resp.api_key;
        console.log(`  API key: ${apiKey}`);
      } else if (resp.error) {
        console.error(`  Signup failed: ${resp.error}`);
        rl?.close();
        process.exit(1);
      } else {
        console.error("  Unexpected response:", JSON.stringify(resp));
        rl?.close();
        process.exit(1);
      }
    } catch (err) {
      console.error(`  Signup failed: ${err.message}`);
      rl?.close();
      process.exit(1);
    }
  }

  // 3. Features
  let enableImages = false;
  let enableIdentity = false;
  if (!nonInteractive) {
    console.log("\nOptional features:");
    enableImages = await askYesNo(
      rl,
      "  Enable image attachments? (attach images to memories via memento_store)",
      false,
    );
    enableIdentity = await askYesNo(
      rl,
      "  Enable identity crystal? (persist a first-person identity snapshot across sessions)",
      false,
    );
  }

  // 4. Agent detection + selection
  const agentKeys = Object.keys(AGENTS);
  const detected = agentKeys.filter((key) => AGENTS[key].detect(cwd));

  let selectedAgents;
  if (nonInteractive) {
    // Auto-detect: use first detected agent, or default to claude-code
    selectedAgents = detected.length > 0 ? [detected[0]] : ["claude-code"];
    console.log(`  Agent: ${AGENTS[selectedAgents[0]].name} (auto-detected)`);
  } else {
    console.log("\nDetected agents:");
    const markers = {
      "claude-code": ".claude/",
      codex: ".codex/",
      gemini: ".gemini/",
      opencode: "opencode.json",
    };
    for (const key of agentKeys) {
      const agent = AGENTS[key];
      const isDetected = detected.includes(key);
      const mark = isDetected ? "✓" : " ";
      const hint = isDetected ? ` (${markers[key]} found)` : "";
      console.log(`    ${mark} ${agent.name}${hint}`);
    }

    console.log("\n  Configure for which agents?");
    agentKeys.forEach((key, i) => {
      const mark = detected.includes(key) ? " ✓" : "";
      console.log(`    ${i + 1}. ${AGENTS[key].name}${mark}`);
    });

    const defaultSelection =
      detected.length > 0
        ? detected.map((key) => agentKeys.indexOf(key) + 1).join(",")
        : "1";
    const selectionStr = await ask(rl, "\n  Enter numbers, comma-separated", defaultSelection);

    const selectedIndices = selectionStr
      .split(",")
      .map((s) => parseInt(s.trim(), 10))
      .filter((n) => n >= 1 && n <= agentKeys.length);
    selectedAgents = [...new Set(selectedIndices.map((i) => agentKeys[i - 1]))];

    if (selectedAgents.length === 0) {
      console.log("  No agents selected. Defaulting to Claude Code.");
      selectedAgents.push("claude-code");
    }
  }

  const hasClaude = selectedAgents.includes("claude-code");

  // 5. Hooks — if any hook-supporting agent is selected (Claude Code, Gemini CLI)
  const hasGemini = selectedAgents.includes("gemini");
  const hasHookAgent = hasClaude || hasGemini;

  let enableUserPrompt = false;
  let enableStop = false;
  let enablePreCompact = false;
  let enableSessionStart = false;

  if (hasHookAgent) {
    if (nonInteractive) {
      // All hooks on by default in non-interactive mode
      enableUserPrompt = true;
      enableStop = true;
      enablePreCompact = true;
      enableSessionStart = false; // identity not enabled in -y mode
    } else {
      console.log("\nAgent hooks (automate recall + distillation):");
      enableUserPrompt = await askYesNo(
        rl,
        "  Prompt recall — recall on every message?",
        true,
      );
      enableStop = await askYesNo(rl, "  Stop — autonomous recall after responses?", true);
      enablePreCompact = await askYesNo(
        rl,
        "  PreCompact — distill memories before context compression?",
        true,
      );
      if (enableIdentity) {
        enableSessionStart = await askYesNo(
          rl,
          "  SessionStart — inject identity + active items at startup?",
          true,
        );
      }
    }
  }

  rl?.close();

  // Build config
  const config = {
    apiKey,
    workspace,
    agents: selectedAgents,
    features: {
      images: enableImages,
      identity: enableIdentity,
    },
    hooks: {
      "userprompt-recall": { enabled: enableUserPrompt },
      "stop-recall": { enabled: enableStop },
      "precompact-distill": { enabled: enablePreCompact },
      "sessionstart-identity": { enabled: enableSessionStart },
    },
  };

  const created = [];

  // 6. Write .memento.json
  const configPath = path.join(cwd, ".memento.json");
  writeJsonFile(configPath, config);
  created.push(".memento.json");

  // 7. Copy hook scripts — gated on any hook-supporting agent
  const hasCodex = selectedAgents.includes("codex");
  const anyHookEnabled =
    enableUserPrompt || enableStop || enablePreCompact || enableSessionStart;

  if (hasHookAgent && anyHookEnabled) {
    const pkgScriptsDir = path.resolve(__dirname, "..", "scripts");
    const localScriptsDir = path.join(cwd, ".memento", "scripts");
    if (!fs.existsSync(localScriptsDir))
      fs.mkdirSync(localScriptsDir, { recursive: true });

    const scriptFiles = [
      "hook-toast.sh",
      enableUserPrompt && "memento-userprompt-recall.sh",
      enableStop && "memento-stop-recall.sh",
      enablePreCompact && "memento-precompact-distill.sh",
      enableSessionStart && "memento-sessionstart-identity.sh",
    ].filter(Boolean);

    // Also copy Codex notify script if Codex is selected
    if (hasCodex) scriptFiles.push("memento-codex-notify.sh");

    for (const name of scriptFiles) {
      const src = path.join(pkgScriptsDir, name);
      if (!fs.existsSync(src)) continue; // skip if script doesn't exist yet
      const dest = path.join(localScriptsDir, name);
      fs.copyFileSync(src, dest);
      fs.chmodSync(dest, 0o755);
    }
    created.push(".memento/scripts/");

    // 7b. Write .memento/version for update checks
    const pkgJsonPath = path.resolve(__dirname, "..", "package.json");
    const pkgVersion = JSON.parse(fs.readFileSync(pkgJsonPath, "utf8")).version;
    const versionPath = path.join(cwd, ".memento", "version");
    fs.writeFileSync(versionPath, pkgVersion + "\n");

    // Hook script commands (absolute paths)
    const recallCmd = path.join(localScriptsDir, "memento-userprompt-recall.sh");
    const stopCmd = path.join(localScriptsDir, "memento-stop-recall.sh");
    const precompactCmd = path.join(localScriptsDir, "memento-precompact-distill.sh");
    const sessionStartCmd = path.join(localScriptsDir, "memento-sessionstart-identity.sh");

    // 8a. Claude Code hooks — .claude/settings.local.json
    if (hasClaude) {
      const settingsPath = path.join(cwd, ".claude", "settings.local.json");
      const settings = readJsonFile(settingsPath) || {};
      let changed = false;
      if (enableUserPrompt) changed = ensureHook(settings, "UserPromptSubmit", recallCmd, 5000) || changed;
      if (enableStop) changed = ensureHook(settings, "Stop", stopCmd, 5000) || changed;
      if (enablePreCompact) changed = ensureHook(settings, "PreCompact", precompactCmd, 30000) || changed;
      if (enableSessionStart) changed = ensureHook(settings, "SessionStart", sessionStartCmd, 10000) || changed;
      if (changed) {
        writeJsonFile(settingsPath, settings);
        created.push(".claude/settings.local.json");
      }
    }

    // 8b. Gemini CLI hooks — .gemini/settings.json
    if (hasGemini) {
      const settingsPath = path.join(cwd, ".gemini", "settings.json");
      const settings = readJsonFile(settingsPath) || {};
      let changed = false;
      if (enableUserPrompt) changed = ensureHook(settings, "BeforeAgent", recallCmd, 5000) || changed;
      if (enableStop) changed = ensureHook(settings, "SessionEnd", stopCmd, 5000) || changed;
      if (enablePreCompact) changed = ensureHook(settings, "PreCompress", precompactCmd, 30000) || changed;
      if (enableSessionStart) changed = ensureHook(settings, "SessionStart", sessionStartCmd, 10000) || changed;
      if (changed) {
        writeJsonFile(settingsPath, settings);
        created.push(".gemini/settings.json (hooks)");
      }
    }
  }

  // 8c. Codex CLI notify — .codex/config.toml (fire-and-forget, post-turn memory storage)
  if (hasCodex) {
    const pkgScriptsDir = path.resolve(__dirname, "..", "scripts");
    const localScriptsDir = path.join(cwd, ".memento", "scripts");
    // Ensure the notify script is copied (may not have been copied above if no hook agent)
    const notifySrc = path.join(pkgScriptsDir, "memento-codex-notify.sh");
    const notifyDest = path.join(localScriptsDir, "memento-codex-notify.sh");
    if (fs.existsSync(notifySrc) && !fs.existsSync(notifyDest)) {
      fs.mkdirSync(localScriptsDir, { recursive: true });
      fs.copyFileSync(notifySrc, notifyDest);
      fs.chmodSync(notifyDest, 0o755);
    }
    const notifyScript = notifyDest;
    const codexTomlPath = path.join(cwd, ".codex", "config.toml");
    let tomlContent = "";
    try { tomlContent = fs.readFileSync(codexTomlPath, "utf-8"); } catch { /* doesn't exist yet */ }
    if (!tomlContent.includes("notify")) {
      const notifyLine = `\nnotify = ["bash", "${notifyScript}"]\n`;
      const separator = tomlContent && !tomlContent.endsWith("\n") ? "\n" : "";
      fs.writeFileSync(codexTomlPath, tomlContent + separator + notifyLine);
      created.push(".codex/config.toml (notify)");
    }
  }

  // 9. Per-agent config files
  for (const agentKey of selectedAgents) {
    const agent = AGENTS[agentKey];
    const result = agent.configWriter(cwd);
    created.push(result);
  }

  // 10. Add .memento.json and .memento/scripts/ to .gitignore
  let gitignoreUpdated = false;
  if (appendToGitignore(cwd, ".memento.json")) gitignoreUpdated = true;
  if (appendToGitignore(cwd, ".memento/scripts/")) gitignoreUpdated = true;
  if (gitignoreUpdated) created.push(".gitignore (updated)");

  // 11. Summary
  const labels = {
    ".memento.json": "workspace config + credentials",
    ".memento/scripts/": "hook scripts (recall + distillation)",
    ".claude/settings.local.json": "hooks registered with Claude Code",
    ".mcp.json": "MCP server registered (Claude Code)",
    ".codex/config.toml": "MCP server registered (Codex)",
    ".codex/config.toml (already configured)": "MCP server (Codex, skipped)",
    ".gemini/settings.json": "MCP server registered (Gemini CLI)",
    "opencode.json": "MCP server registered (OpenCode)",
    ".gitignore (updated)": "credentials excluded from git",
  };
  const colWidth = Math.max(...created.map((f) => f.length)) + 2;
  console.log("\n  ✓ Memento is live.\n");
  console.log("  Created:");
  for (const f of created) {
    const label = labels[f] || "";
    console.log(`    ${f.padEnd(colWidth)}${label}`);
  }

  // Per-agent next steps
  console.log("\n  Next steps:");
  for (const agentKey of selectedAgents) {
    const agent = AGENTS[agentKey];
    console.log(`    · ${agent.name}: ${agent.nextSteps}`);
  }
  console.log("  Your agent will wake up remembering.\n");

  // 12. Auto-integrate agent instructions
  const primaryAgent = selectedAgents[0];
  const prompt = buildIntegrationPrompt(INSTRUCTIONS_BLOB);
  const cmdParts = HEADLESS_CMDS[primaryAgent]?.(prompt);

  if (nonInteractive) {
    // Auto-run headless integration, no prompt
    if (cmdParts) {
      console.log(`  Integrating instructions via ${AGENTS[primaryAgent].name}...`);
      const result = runAgentHeadless(primaryAgent, prompt);
      if (result !== null) {
        console.log(result);
      } else {
        // Fallback: print the blob
        console.log("  Agent integration failed — paste these instructions manually:\n");
        printInstructionsFallback(selectedAgents);
      }
    } else {
      printInstructionsFallback(selectedAgents);
    }
  } else {
    // Interactive: ask with explicit command shown
    if (cmdParts) {
      const [cmd, ...args] = cmdParts;
      const flagArgs = args.slice(0, -1).join(" ");
      const displayCmd = `${cmd} ${flagArgs} <prompt>`;
      const rl2 = readline.createInterface({ input: process.stdin, output: process.stdout });
      console.log("─".repeat(60));
      const integrate = await askYesNo(
        rl2,
        `\n  Auto-integrate instructions into your project?\n  This will run: ${displayCmd}\n\n  ⚠  This uses --dangerously-skip-permissions so the agent can\n  write to CLAUDE.md without prompting. If you prefer, decline\n  and we'll print the instructions for you to add manually.\n\n  Proceed?`,
        true,
      );
      rl2.close();

      if (integrate) {
        console.log(`\n  Running ${AGENTS[primaryAgent].name}...`);
        const result = runAgentHeadless(primaryAgent, prompt);
        if (result !== null) {
          console.log(result);
        } else {
          console.log("  Agent integration failed — paste these instructions manually:\n");
          printInstructionsFallback(selectedAgents);
        }
      } else {
        printInstructionsFallback(selectedAgents);
      }
    } else {
      printInstructionsFallback(selectedAgents);
    }
  }
}

// ---------------------------------------------------------------------------
// Update command — copy fresh hook scripts to an existing installation
// ---------------------------------------------------------------------------

async function runUpdate() {
  const cwd = process.cwd();
  const configPath = path.join(cwd, ".memento.json");

  if (!fs.existsSync(configPath)) {
    console.error(
      "  Error: .memento.json not found in current directory.\n" +
        "  Run `npx memento-mcp init` first to set up Memento.\n"
    );
    process.exit(1);
  }

  const pkgJsonPath = path.resolve(__dirname, "..", "package.json");
  const pkgVersion = JSON.parse(fs.readFileSync(pkgJsonPath, "utf8")).version;

  const pkgScriptsDir = path.resolve(__dirname, "..", "scripts");
  const localScriptsDir = path.join(cwd, ".memento", "scripts");

  if (!fs.existsSync(localScriptsDir)) {
    fs.mkdirSync(localScriptsDir, { recursive: true });
  }

  // Copy all .sh files from package scripts/ to local .memento/scripts/
  const scriptFiles = fs
    .readdirSync(pkgScriptsDir)
    .filter((f) => f.endsWith(".sh"));

  const updated = [];
  for (const name of scriptFiles) {
    const src = path.join(pkgScriptsDir, name);
    const dest = path.join(localScriptsDir, name);
    fs.copyFileSync(src, dest);
    fs.chmodSync(dest, 0o755);
    updated.push(name);
  }

  // Write .memento/version
  const versionPath = path.join(cwd, ".memento", "version");
  fs.writeFileSync(versionPath, pkgVersion + "\n");

  // Ensure SessionStart hook is registered for agents that support hooks
  // Detect by config agents field or directory presence (older configs may lack agents)
  const config = readJsonFile(configPath) || {};
  const agents = config.agents || [];
  const sessionStartCmd = path.join(localScriptsDir, "memento-sessionstart-identity.sh");
  const registeredHooks = [];

  // Claude Code
  const hasClaude = agents.includes("claude-code")
    || fs.existsSync(path.join(cwd, ".claude"));
  if (hasClaude) {
    const settingsPath = path.join(cwd, ".claude", "settings.local.json");
    const settings = readJsonFile(settingsPath) || {};
    if (ensureHook(settings, "SessionStart", sessionStartCmd, 10000)) {
      writeJsonFile(settingsPath, settings);
      registeredHooks.push("Claude Code → .claude/settings.local.json");
    }
  }

  // Gemini CLI
  const hasGemini = agents.includes("gemini")
    || fs.existsSync(path.join(cwd, ".gemini"));
  if (hasGemini) {
    const settingsPath = path.join(cwd, ".gemini", "settings.json");
    const settings = readJsonFile(settingsPath) || {};
    if (ensureHook(settings, "SessionStart", sessionStartCmd, 10000)) {
      writeJsonFile(settingsPath, settings);
      registeredHooks.push("Gemini CLI → .gemini/settings.json");
    }
  }

  // Codex CLI — ensure notify is configured
  const hasCodex = agents.includes("codex")
    || fs.existsSync(path.join(cwd, ".codex"));
  if (hasCodex) {
    const notifyScript = path.join(localScriptsDir, "memento-codex-notify.sh");
    const codexTomlPath = path.join(cwd, ".codex", "config.toml");
    let tomlContent = "";
    try { tomlContent = fs.readFileSync(codexTomlPath, "utf-8"); } catch { /* doesn't exist yet */ }
    if (!tomlContent.includes("notify") && fs.existsSync(notifyScript)) {
      const notifyLine = `\nnotify = ["bash", "${notifyScript}"]\n`;
      const separator = tomlContent && !tomlContent.endsWith("\n") ? "\n" : "";
      fs.mkdirSync(path.dirname(codexTomlPath), { recursive: true });
      fs.writeFileSync(codexTomlPath, tomlContent + separator + notifyLine);
      registeredHooks.push("Codex CLI → .codex/config.toml (notify)");
    }
  }

  console.log(`\n  ✓ Memento hooks updated to v${pkgVersion}\n`);
  console.log("  Updated scripts:");
  for (const name of updated) {
    console.log(`    ${name}`);
  }
  if (registeredHooks.length > 0) {
    console.log("\n  Registered hooks:");
    for (const hook of registeredHooks) {
      console.log(`    ${hook}`);
    }
  }
  console.log(`\n  Version written to .memento/version`);
  console.log("  Restart your agent session to pick up changes.\n");
}

function printInstructionsFallback(selectedAgents) {
  const hasNonClaude = selectedAgents.some((k) => k !== "claude-code");
  const docTarget = hasNonClaude
    ? "your CLAUDE.md, AGENTS.md, or equivalent"
    : "your CLAUDE.md";

  console.log("─".repeat(60));
  console.log(`
  One more step: paste the following into ${docTarget},
  or hand it to your agent and ask it to add it. This teaches
  your agent the memory discipline Memento expects.

  ── paste below this line ──────────────────────────────

${INSTRUCTIONS_BLOB}

  ── paste above this line ──────────────────────────────
`);
}

// ---------------------------------------------------------------------------
// Entrypoint — only run when this module is the entry point (not imported)
// ---------------------------------------------------------------------------

const isMain =
  process.argv[1] &&
  (process.argv[1].endsWith("/cli.js") || process.argv[1].endsWith("memento-mcp"));

if (isMain) {
  const args = process.argv.slice(2);

  if (args[0] === "init") {
    const flags = parseFlags(args.slice(1));
    runInit(flags).catch((err) => {
      console.error(err);
      process.exit(1);
    });
  } else if (args[0] === "update") {
    runUpdate().catch((err) => {
      console.error(err);
      process.exit(1);
    });
  } else if (args.length === 0) {
    // No args — start the MCP server (this is what .mcp.json invokes)
    // Must call main() explicitly because the isMainModule guard in index.js
    // checks process.argv[1] which still points to cli.js, not index.js.
    const { main } = await import("./index.js");
    await main();
  } else {
    console.log(`
  Memento Protocol CLI

  Usage:
    npx memento-mcp init                Set up Memento in the current project
    npx memento-mcp init -y             Non-interactive setup (uses defaults)
    npx memento-mcp init --api-key KEY  Provide API key (skips signup)
    npx memento-mcp update              Update hook scripts to latest version
    npx memento-mcp                     Start the MCP server (used by .mcp.json)

  The -y flag enables fully non-interactive setup for CI/scripting.
  Combine with --api-key to skip auto-signup.

  Supports Claude Code, Codex, Gemini CLI, and OpenCode.
`);
    process.exit(1);
  }
}
